### ISSUE TITLE
project not work

### ISSUE THREAD

**Issue by Hyodori04** [MaxKim-J/module-federation-example#1]
I followed step in read me. But it not works

```
 module-federation-example % yarn turbo:start          
╭───────────────────────────────────────────────────────────────────────╮
│                                                                       │
│                  Update available v1.10.3 ≫ v1.11.3                   │
│    Changelog: https://github.com/vercel/turbo/releases/tag/v1.11.3    │
│               Run "npx @turbo/codemod update" to update               │
│                                                                       │
│     Follow @turborepo for updates: https://twitter.com/turborepo      │
╰───────────────────────────────────────────────────────────────────────╯
• Packages in scope: @module-federation-example/micro-app-a, @module-federation-example/micro-app-b, @module-federation-example/micro-app-c
• Running start in 3 packages
• Remote caching disabled
@module-federation-example/micro-app-b:start: cache miss, executing 66734fa6b4c6502b
@module-federation-example/micro-app-c:start: cache miss, executing fb5ca07e4b706955
@module-federation-example/micro-app-a:start: cache miss, executing cc0b762bac47a922
@module-federation-example/micro-app-c:start: Type Error: Cannot read properties of undefined (reading '/Users/user/module-federation-example/.pnp.cjs')
@module-federation-example/micro-app-c:start:     at c4 (/Users/user/module-federation-example/.yarn/releases/yarn-3.6.0.cjs:390:12692)
@module-federation-example/micro-app-c:start:     at a0e (/Users/user/module-federation-example/.yarn/releases/yarn-3.6.0.cjs:390:13173)
@module-federation-example/micro-app-c:start:     at Object.mf (/Users/user/module-federation-example/.yarn/releases/yarn-3.6.0.cjs:390:13402)
@module-federation-example/micro-app-c:start:     at /Users/user/module-federation-example/.yarn/releases/yarn-3.6.0.cjs:694:4611
@module-federation-example/micro-app-c:start:     at Object.Ta (/Users/user/module-federation-example/.yarn/releases/yarn-3.6.0.cjs:390:10714)
@module-federation-example/micro-app-c:start:     at wl.findPackageLocation (/Users/user/module-federation-example/.yarn/releases/yarn-3.6.0.cjs:694:4566)
@module-federation-example/micro-app-c:start:     at /Users/user/module-federation-example/.yarn/releases/yarn-3.6.0.cjs:423:1264
@module-federation-example/micro-app-c:start:     at Function.from (<anonymous>)
@module-federation-example/micro-app-c:start:     at LB (/Users/user/module-federation-example/.yarn/releases/yarn-3.6.0.cjs:423:1008)
@module-federation-example/micro-app-c:start:     at d9 (/Users/user/module-federation-example/.yarn/releases/yarn-3.6.0.cjs:423:1589)
@module-federation-example/micro-app-a:start: Type Error: Cannot read properties of undefined (reading '/Users/user/module-federation-example/.pnp.cjs')
@module-federation-example/micro-app-a:start:     at c4 (/Users/user/module-federation-example/.yarn/releases/yarn-3.6.0.cjs:390:12692)
@module-federation-example/micro-app-a:start:     at a0e (/Users/user/module-federation-example/.yarn/releases/yarn-3.6.0.cjs:390:13173)
@module-federation-example/micro-app-a:start:     at Object.mf (/Users/user/module-federation-example/.yarn/releases/yarn-3.6.0.cjs:390:13402)
@module-federation-example/micro-app-a:start:     at /Users/user/module-federation-example/.yarn/releases/yarn-3.6.0.cjs:694:4611
@module-federation-example/micro-app-a:start:     at Object.Ta (/Users/user/module-federation-example/.yarn/releases/yarn-3.6.0.cjs:390:10714)
@module-federation-example/micro-app-a:start:     at wl.findPackageLocation (/Users/user/module-federation-example/.yarn/releases/yarn-3.6.0.cjs:694:4566)
@module-federation-example/micro-app-a:start:     at /Users/user/module-federation-example/.yarn/releases/yarn-3.6.0.cjs:423:1264
@module-federation-example/micro-app-a:start:     at Function.from (<anonymous>)
@module-federation-example/micro-app-a:start:     at LB (/Users/user/module-federation-example/.yarn/releases/yarn-3.6.0.cjs:423:1008)
@module-federation-example/micro-app-a:start:     at d9 (/Users/user/module-federation-example/.yarn/releases/yarn-3.6.0.cjs:423:1589)
@module-federation-example/micro-app-c:start: ERROR: command finished with error: command (/Users/user/module-federation-example/micro-app-c) yarn run start exited (1)
@module-federation-example/micro-app-a:start: ERROR: command finished with error: command (/Users/user/module-federation-example/micro-app-a) yarn run start exited (1)
command (/Users/user/module-federation-example/micro-app-c) yarn run start exited (1)
command (/Users/user/module-federation-example/micro-app-a) yarn run start exited (1)

 Tasks:    0 successful, 3 total
Cached:    0 cached, 3 total
  Time:    688ms 
Failed:    @module-federation-example/micro-app-a#start, @module-federation-example/micro-app-c#start

 ERROR  run failed: command  exited (1)

```

**Comment by metacode22** [comment]
.yarnrc.yml에서 nodeLinker를 `node-modules`로 변경하고

다음 명령어를 통해 pnp 관련된 것들을 정리한 다음
```bash
rm -rf node_modules .pnp.* .yarn/cahce
```

다시 yarn install, yarn turbo:start 하니 동작하네요.

즉 zero-install 포기하고 그냥 돌리니까 동작을 확인할 수 있긴 하네요!
